---
title: "300 Analysis"
author: "Julia Ting"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rio)
library(tidyverse)
library(ggplot2)
library(stargazer)
library(car)
library(mgcv)
library(broom)
library(boot)
```

```{r}
df = import("ed_tweets_final.csv")

## Convert dependent to numeric type
df["followers"] = as.numeric(df["followers"][[1]])

## Shifted log transform variables
df <- df %>%
  mutate(t_followers = (df$followers - mean(df$followers))/sd(df$followers),
         log_followers = log(df$followers + 1),
         log_following = log(df$following + 1),
         log_statuses = log(df$statuses + 1),
         desc_label = as.factor(desc_label),
         pro_recovery = as.factor(pro_recovery),
         weight_label = as.factor(weight_label),
         tw_label = as.factor(tw_label),
         vent_label = as.factor(vent_label),
         sh_label = as.factor(sh_label))
```

```{r}
## Get rid of observations with outlier follower counts
trunc_df <- filter(df, t_followers <= 3 & t_followers >= -3)
```




```{r}
## Check that log_followers is normally distributed
ggplot(data =trunc_df, aes(x=log_followers, fill=as.factor(desc_label))) + geom_histogram(bins=50) + labs(title="Histogram of Log Follower Counts", x="Log(Followers + 1)", y="Count", fill="Pro-ED") + scale_fill_discrete(labels=c('False', 'True')) + geom_vline(xintercept=mean(trunc_df["log_followers"][df["desc_label"] == 1], na.rm=TRUE)) + geom_vline(xintercept=mean(trunc_df["log_followers"][df["desc_label"] == 0], na.rm=TRUE))


```

```{r}
## See if there appears to be a difference in follower counts for pro-ED and non-ED accounts
ggplot(data =trunc_df, aes(y=log_followers, x=as.factor(desc_label), fill=as.factor(desc_label))) +
  geom_boxplot()+ 
  labs(title="Boxplot of Log Follower Counts", y="Log(Followers + 1)", x="Pro-ED or Not", fill="Pro-ED") +
  scale_x_discrete(labels=c('0' = "Not Pro-ED", "1" = "Pro-ED"))+ scale_fill_discrete(labels=c('False', 'True')) 
```



```{r}
## Formally test difference in followers with t-test
t.test(trunc_df["log_followers"][df["desc_label"] == 1], trunc_df["log_followers"][df["desc_label"] == 0],
       alternative = "less")
```

```{r}
## Just pro-ED accounts
ed_trunc_df <- filter(trunc_df, desc_label == 1)
```


```{r}
## Check for linear relationship btwn log_statuses and log_followers
ggplot(data = ed_trunc_df, aes(x=log_statuses, y=log_followers)) + geom_point()
```

```{r}
## Check for linear relationship btwn log_following and log_followers
ggplot(data = ed_trunc_df, aes(x=log_following, y=log_followers)) + geom_point()
```

```{r}
## Creating different models
log_modela <- lm(log_followers~pro_recovery+weight_label+tw_label+sh_label+vent_label+log_following+log_statuses, data = ed_trunc_df)

log_modelb <- lm(log_followers~weight_label+tw_label+sh_label+vent_label+log_following+log_statuses, data = ed_trunc_df)

log_modelc <- lm(log_followers~tw_label+log_following+log_statuses+vent_label, data = ed_trunc_df)

log_modeld <- lm(log_followers~log_following+log_statuses, data = ed_trunc_df)

log_modele <- lm(log_followers~weight_label+tw_label+vent_label+log_following+log_statuses, data = ed_trunc_df)

log_modela$AIC <- AIC(log_modela)
log_modelb$AIC <- AIC(log_modelb)
log_modelc$AIC <- AIC(log_modelc)
log_modeld$AIC <- AIC(log_modeld)
log_modele$AIC <- AIC(log_modele)

log_modela$BIC <- BIC(log_modela)
log_modelb$BIC <- BIC(log_modelb)
log_modelc$BIC <- BIC(log_modelc)
log_modeld$BIC <- BIC(log_modeld)
log_modele$BIC <- BIC(log_modele)

stargazer(log_modela, log_modelb, log_modelc, log_modeld, log_modele, type="text", header=FALSE,
          title="Predicting Follower Count in ED Accounts", covariate.labels = c("Pro Recovery", "Mentions Weight", "Includes Trigger Warning", "Mentions Self-Hate", "Vent", "Log(Following + 1)", "Log(Statuses + 1)"), dep.var.labels = "Log(Followers + 1)",
          keep.stat=c("aic", "bic", "adj.rsq", "n"))
```



```{r}
set.seed(2021)

glm_b <- glm(log_followers~weight_label+tw_label+sh_label+vent_label+log_following+log_statuses, data = ed_trunc_df)

glm_c <- glm(log_followers~tw_label+log_following+log_statuses+vent_label, data = ed_trunc_df)

glm_d <- glm(log_followers~log_following+log_statuses, data = ed_trunc_df)
## let's look at cross validations of 2,3,4 which need to be glms
cv.glm(ed_trunc_df, glm_b, K = 20)$delta

cv.glm(ed_trunc_df, glm_c, K = 20)$delta

cv.glm(ed_trunc_df, glm_d, K = 20)$delta
```
The best model is model b with the lowest cross validation errors

```{r}
vif(log_modelb)
```

```{r}
summary(log_modelb)
```

```{r}

resid_data <- augment(log_modelb)
ggplot(resid_data, aes(.resid))+geom_histogram(binwidth = 0.5) + labs(x = "Residual", y= "Count", title = "Histogram of Residuals from Linear Model")
```


```{r}
ggplot(resid_data, aes(x=.fitted, y=.resid))+geom_point(alpha=0.2)+ geom_hline(yintercept = 0, color = "Red") + labs(x = "Fitted value", y = "Residual", title="Fitted Values and Residuals of Model")
```




